talk crud & new confa migrations
aromancev/confa pull request #24
Opened 2021-03-21 12:39 UTC by buzyakabarbuzyaka

Talk crud and confa migrations added.

2021-03-21 14:23 UTC, aromancev requested changes

2021-03-21 14:23 UTC, aromancev commented on api/cmd/api/handler/http.go
> +		log.Ctx(ctx).Err(err).Msg("Failed to create confa")
```suggestion
		log.Ctx(ctx).Err(err).Msg("Failed to create talk")
```

2021-03-21 14:23 UTC, aromancev commented on api/cmd/api/handler/http.go
> +	conf, err := h.talkCRUD.Create(ctx, userID, request)
```suggestion
	talk, err := h.talkCRUD.Create(ctx, userID, request)
```

2021-03-21 14:23 UTC, aromancev commented on api/cmd/api/handler/http.go
> +	conf, err := h.talkCRUD.Fetch(ctx, talkID)
```suggestion
	talk, err := h.talkCRUD.Fetch(ctx, talkID)
```

2021-03-21 14:23 UTC, aromancev commented on api/cmd/api/handler/http.go
> +		log.Ctx(ctx).Err(err).Msg("Failed to fetch confa")
```suggestion
		log.Ctx(ctx).Err(err).Msg("Failed to fetch talk")
```

2021-03-21 15:09 UTC, aromancev approved these changes

2021-03-25 17:02 UTC, aromancev requested changes

2021-03-25 17:02 UTC, aromancev commented on api/cmd/api/handler/http.go
> +	case errors.Is(err, talk.ErrValidation):
It's impossible to get `ErrValidation` if we are fetching a talk, right?
There is nothing to validate. If code returns this error, it's probably a mistake, and should be handled by `err != nil` clause.

2021-03-25 17:02 UTC, aromancev commented on api/internal/confa/confa.go
> +	validHandle := regexp.MustCompile("^[A-z,0-9]{1,64}$")
Compiling regex for each request is a bad practice because It's quite expensive. For this reason, we should compile it once (define it as a global var).

2021-03-25 17:02 UTC, aromancev commented on api/internal/confa/sql_test.go
> +	t.Run("Handle-UUID", func(t *testing.T) {
This is also a `Create` test. Let's put this inside `Create` sub-test. Like this:
```
t.Run("Create", func(t *testing.T) {
    t.Run("Happy path", func(t *testing.T) {
        // The code that was inside `Create` before.
    }
     t.Run("Handle holds UUID", func(t *testing.T) {
        // The code that you added in `Handle-UUID`.
     }
     // Other cases for `Create` functon.
}
```

2021-03-25 17:02 UTC, aromancev commented on api/internal/confa/sql_test.go
> +	t.Run("Duplicated Entry", func(t *testing.T) {
This is also a Create test. Let's put this inside Create sub-test. Like this:
```
t.Run("Create", func(t *testing.T) {
    t.Run("Happy path", func(t *testing.T) {
        // The code that was inside `Create` before.
    }
     t.Run("Creating duplicate returns correct error", func(t *testing.T) {
        // The code that you added in `Duplicated Entry`.
     }
     // Other cases for `Create` functon.
}
```

2021-03-25 17:02 UTC, aromancev commented on api/internal/confa/sql_test.go
> +		fetched, err := sql.Fetch(ctx, pg, Lookup{
No need to assert this anymore. We already checked that Confa is saved correctly in another test. We can just do this:
```
_, err := sql.Create(ctx, pg, request)
require.NoError(t, err)
```

2021-03-25 17:02 UTC, aromancev commented on api/internal/confa/sql_test.go
> +		assert.Equal(t, err, ErrDuplicatedEntry)
This `assert` method is not what we want, unfortunately. It compares errors as values. So, for example, this will work:
```
assert.Equal(t, errors.New("test"), errors.New("test"))
```

We don't want that. We want to check that this method returned the error we defined. So, we should do this instead:
```
assert.True(t, err == ErrDuplicatedEntry)
```

2021-03-25 17:02 UTC, aromancev commented on api/internal/confa/talk/service.go
> +func (c *CRUD) Create(ctx context.Context, confaID uuid.UUID, request Talk) (Talk, error) {
We also need `userID` here (and also we need to add `Owner != uuid.Nil` in `Validate` method). We want all objects created by a user to belong to this user.

We also don't want users to be able to create a Talk for someone else's Confa. So we need to fetch this Confa by it's id and check if it's the same user.

2021-03-25 17:02 UTC, aromancev commented on api/internal/confa/talk/service.go
> +		return Talk{}, fmt.Errorf("failed to create confa: %w", err)
```suggestion
		return Talk{}, fmt.Errorf("failed to create talk: %w", err)
```

2021-03-25 17:02 UTC, aromancev commented on api/internal/confa/talk/service.go
> +		return Talk{}, fmt.Errorf("failed to fetch confa: %w", err)
```suggestion
		return Talk{}, fmt.Errorf("failed to fetch talk: %w", err)
```

2021-03-25 17:02 UTC, aromancev commented on api/internal/confa/talk/sql_test.go
> +	t.Run("Handle-UUID", func(t *testing.T) {
This is also a `Create` test. Let's put this inside `Create` sub-test. Like this:
```
t.Run("Create", func(t *testing.T) {
    t.Run("Happy path", func(t *testing.T) {
        // The code that was inside `Create` before.
    }
     t.Run("Handle holds UUID", func(t *testing.T) {
        // The code that you added in `Handle-UUID`.
     }
     // Other cases for `Create` functon.
}
```

2021-03-25 17:02 UTC, aromancev commented on api/internal/confa/talk/sql_test.go
> +		assert.Equal(t, createdTalk, fetchedTalk)
No need to assert this anymore. We already checked that Talk is saved correctly in another test. We can just do this:
```
_, err := talks.Create(ctx, pg, requestTalk)
require.NoError(t, err)
```

2021-03-25 17:02 UTC, aromancev commented on api/internal/confa/talk/sql_test.go
> +	t.Run("Duplicated Entry", func(t *testing.T) {
This is also a Create test. Let's put this inside Create sub-test. Like this:
```
t.Run("Create", func(t *testing.T) {
    t.Run("Happy path", func(t *testing.T) {
        // The code that was inside `Create` before.
    }
     t.Run("Creating duplicate returns correct error", func(t *testing.T) {
        // The code that you added in `Duplicated Entry`.
     }
     // Other cases for `Create` functon.
}
```

2021-03-25 17:02 UTC, aromancev commented on api/internal/confa/talk/sql_test.go
> +		assert.Equal(t, err, ErrDuplicatedEntry)
This `assert` method is not what we want, unfortunately. It compares errors as values. So, for example, this will work:
```
assert.Equal(t, errors.New("test"), errors.New("test"))
```

We don't want that. We want to check that this method returned the error we defined. So, we should do this instead:
```
assert.True(t, err == ErrDuplicatedEntry)
```

2021-03-25 17:02 UTC, aromancev commented on api/internal/confa/talk/talk.go
> +	validHandle := regexp.MustCompile("^[A-z,0-9]{1,64}$")
Compiling regex for each request is a bad practice because It's quite expensive. For this reason, we should compile it once (define it as a global var).

2021-03-25 17:02 UTC, aromancev commented on api/internal/confa/talk/talk.go
> +		return errors.New("owner should not be empty")
```suggestion
		return errors.New("confa should not be empty")
```

And also need a check for owner :)

2021-03-25 17:02 UTC, aromancev commented on api/internal/user/sql_test.go
> +func TestSQL(t *testing.T) {
👍

2021-03-25 18:26 UTC, a-romancev commented on api/internal/confa/talk/talk.go
> +		return errors.New("owner should not be empty")
still need 2 add owner field to Talk

2021-03-30 17:37 UTC, merged