Session crud
aromancev/confa pull request #31
Opened 2021-03-28 14:35 UTC by buzyakabarbuzyaka

2021-03-28 14:42 UTC, buzyakabarbuzyaka commented on api/cmd/api/handler/handler.go
> +	r.GET("/confa/v1/sessions", h.session) // unmarshal session key from request
Base64 can contain '/' symbol. It destroys routing.

2021-03-28 14:46 UTC, buzyakabarbuzyaka commented on api/cmd/api/handler/http.go
> +	sess, err := h.sessionCRUD.Create(ctx, userID, request)
This route was made to test fetch logics in session witch might be unnecessary.

2021-03-28 16:14 UTC, aromancev requested changes

2021-03-28 16:14 UTC, aromancev commented on api/internal/user/session/session.go
> +const byteKeyLength = 96 // you need 4*(n/3) chars to represent n bytes
```suggestion
const keyLength = 96 // you need 4*(n/3) chars to represent n bytes
```

2021-03-28 16:14 UTC, aromancev commented on api/internal/user/session/session.go
> +func (s Session) GenerateKey() (Session, error) {
```suggestion
func (s Session) New() Session {
```

`GenerateKey`  sounds like it should return some kind of key. But in fact it returns `Session`. Let's make it a constructor instead.

2021-03-28 16:14 UTC, aromancev commented on api/internal/user/session/session.go
> +func generateKey() string {
If it's only used inside `GenerateKey` maybe we should just copy-paste this code there?

2021-03-28 16:14 UTC, aromancev commented on api/internal/user/session/session.go
> +func (s Session) Validate() error {
Also need to check if key is not empty.

2021-04-04 13:35 UTC, aromancev approved these changes

2021-04-04 13:35 UTC, aromancev commented on api/internal/auth/auth.go
> +func TokenHelper(rawToken string) (string, error) {
```suggestion
func Bearer(r *http.Request) (string, error) {
```

2021-04-04 13:35 UTC, aromancev commented on api/internal/auth/auth.go
> +		return "", errors.New("header format error")
```suggestion
		return "", errors.New("wrong header format")
```

2021-04-04 13:35 UTC, aromancev commented on api/internal/auth/auth.go
> +		return "", errors.New("header type format error")
```suggestion
		return "", errors.New("wrong type")
```

2021-04-04 13:35 UTC, aromancev commented on api/internal/user/session/session.go
> +	return s
```suggestion
	return Session{Key: key}
```

2021-04-04 15:36 UTC, merged