Claps
aromancev/confa pull request #56
Opened 2021-04-29 17:45 UTC by a-romancev

2021-04-29 18:38 UTC, aromancev requested changes

2021-04-29 18:38 UTC, aromancev commented on api/cmd/api/handler/handler.go
> +		"/confa/v1/confas/:confa_id/claps",
Let's combine these endpoints into one with query params.

2021-04-29 18:38 UTC, aromancev commented on api/cmd/api/handler/http.go
> +		if request.Confa == uuid.Nil {
This should be in the service. Only accept talk from the request and fetch it from DB.

2021-04-29 18:38 UTC, aromancev commented on api/cmd/api/handler/http.go
> +		var lookup clap.Lookup
```suggestion
		lookup clap.Lookup{
		    Confa: confaID,
		}
```

2021-04-29 18:38 UTC, aromancev commented on api/internal/confa/migrations/001_init.sql
> +    id UUID PRIMARY KEY,
Let's use (owner, talk) as primary key to save a bit of space.

2021-04-29 18:38 UTC, aromancev commented on api/internal/confa/talk/clap/service.go
> +	request.Speaker = ownerID
Speaker should come from the talk.

2021-04-29 18:38 UTC, aromancev commented on api/internal/confa/talk/clap/service.go
> +func (c *CRUD) Aggregate(ctx context.Context, lookup Lookup) (int, error) {
No need for this function. We can just call `repo.Aggregate` in the handler.

2021-04-29 18:38 UTC, aromancev commented on api/internal/confa/talk/clap/service_test.go
> +	t.Run("FetchByTalk", func(t *testing.T) {
`CRUD` has no function `FetchByTalk`.  It should be called `CreateOrUpdate`. This test should just create some claps, then fetch then call `Aggregate` to verify that the number of claps is ok. We can even use [table tests](https://github.com/golang/go/wiki/TableDrivenTests) for that.

2021-04-29 18:38 UTC, aromancev commented on api/internal/confa/talk/clap/sql.go
> +		return fmt.Errorf("invalid request : %w", err)
```suggestion
		return err
```

2021-04-29 18:38 UTC, aromancev commented on api/internal/confa/talk/clap/sql.go
> +	case errors.As(err, &pgErr):
Since we use `upsert`, this should never return this error. Let's just remove this case.

2021-04-29 18:38 UTC, aromancev commented on api/internal/confa/talk/clap/sql.go
> +	for rows.Next() {
We should not select all claps and then sum them all in the application. Instead, we should select `SUM` postgres aggregation func. It will return a single row with already aggregated number of claps.

2021-04-29 18:38 UTC, aromancev commented on api/internal/confa/talk/clap/sql_test.go
> +	t.Run("Create", func(t *testing.T) {
```suggestion
	t.Run("CreateOrUpdate", func(t *testing.T) {
```

2021-04-29 18:38 UTC, aromancev commented on api/internal/confa/talk/clap/sql_test.go
> +	t.Run("Create", func(t *testing.T) {
This test does not check the result of the operation. We need to check if `Aggregate` returns a correct value.

2021-04-29 18:38 UTC, aromancev commented on api/internal/confa/talk/service_test.go
> +			Speaker: userID,
This should be done inside `talkCRUD.Create`.

2021-04-29 18:38 UTC, aromancev commented on api/internal/confa/talk/sql_test.go
> +				Speaker:  userID,
This should be done inside `talkCRUD.Create`.

2021-05-06 17:24 UTC, aromancev requested changes

2021-05-06 17:24 UTC, aromancev commented on api/internal/confa/talk/clap/sql.go
> +	q := sq.Select("claps").From("claps")
```suggestion
	q := sq.Select("SUM(claps)").From("claps")
```
```suggestion
	q := sq.Select("claps").From("claps")
```

2021-06-20 14:34 UTC, a-romancev commented on api/internal/confa/talk/clap/service.go
> +func (c *CRUD) Aggregate(ctx context.Context, lookup Lookup) (int, error) {
?

2021-06-20 14:35 UTC, a-romancev commented on api/internal/confa/talk/clap/service_test.go
> +	t.Run("FetchByTalk", func(t *testing.T) {
?

2021-07-03 10:31 UTC, aromancev requested changes

2021-07-03 10:31 UTC, aromancev commented on Makefile
> +	cd ./api/cmd/api && go build -o ./ && rm api
```suggestion
	cd api \
	    && go build -o bin/ cmd/api/... \
	    && go build -o bin/ cmd/media/... \
	    && go build -o bin/ cmd/sfu/...
```

2021-07-03 10:31 UTC, aromancev commented on api/internal/confa/talk/clap/service.go
> +		return fmt.Errorf("failed to create clap: %w", err)
If talk was not found, this would be an internal error. It should be a "bad request" instead. For example, `ErrValidation` to something like this.

2021-07-03 10:31 UTC, aromancev commented on api/internal/confa/talk/clap/service_test.go
> +		requestClap := Clap{
Isn't it easier to just do this
```
err = clapCRUD.CreateOrUpdate(ctx, ids[0], Clap{Talk: requestTalks[0].ID, Claps: 1})
```
instead of declaring `requestClap`, `requestClap2`, etc?

At the very least, you can just reuse the same `requestClap`.

2021-07-03 10:31 UTC, aromancev commented on api/internal/confa/talk/clap/sql_test.go
> +			require.NoError(t, err)
"Happy path" test should also verify the `aggregate` result verifying that `CreateOrUpdate` created correct data.
Same for "Create and Update".

And we can remove "Create and Aggregate" and "Create, Update and Aggregate", because it's already covered.

2021-07-03 10:31 UTC, aromancev commented on api/internal/confa/talk/clap/sql_test.go
> +		t.Run("Aggregate by Confa", func(t *testing.T) {
That's another subtest. Currently this is inside "CreateOrUpdate" test, but it's testing "Aggregate" function. It should be separate.

2021-07-04 13:08 UTC, merged